---

- name: Create a started container
  community.general.lxd_container:
    name: microk8s
    ignore_volatile_options: true
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: simplestreams
      alias: ubuntu/focal/amd64
    profiles: ["default", "microk8s"]
    wait_for_ipv4_addresses: true
    timeout: 600

- name: Adding second interface
  ansible.builtin.command: lxc config device add microk8s eth1 nic name=eth1 nictype=bridged parent=bridge0

- name: Adding bridge profile
  ansible.builtin.command: lxc profile assign microk8s default,microk8s,bridgeprofile
# notify: Restart microk8s

- name: Install snapd
  ansible.builtin.command: lxc exec microk8s -- sudo apt install snapd -y

- name: Install micrko8s
  ansible.builtin.command: lxc exec microk8s -- sudo snap install microk8s --classic

- name: Copying tmp (microk8s_rc.local) files to lxd_host
  ansible.builtin.copy:
    src: ../files/microk8s_rc.local
    dest: /tmp/microk8s_rc.local

- name: Copying tmp files (microk8s_netplan.yaml) to lxd_host
  ansible.builtin.copy:
    src: ../files/microk8s_netplan.yaml
    dest: /tmp/microk8s_netplan.yaml

- name: Copying rc.local to microk8s
  ansible.builtin.command: lxc file push /tmp/microk8s_rc.local microk8s/etc/rc.local

- name: Copying netplan file to microk8s
  ansible.builtin.command: lxc file push /tmp/microk8s_netplan.yaml microk8s/etc/netplan/99-eth1.yaml

- name: Updating rc.local permissions in microk8s
  ansible.builtin.command: lxc exec microk8s -- chmod +x /etc/rc.local 
  notify: 
#   - Restart microk8s
    - Reboot


    
